AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: mi-boda-service

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs20.x

Resources:
  FormDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FormData
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  SubmitFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.submitForm
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FormDataTable
      Events:
        ApiPost:
          Type: Api
          Properties:
            Path: /submit
            Method: POST
            RestApiId: !Ref ServerlessRestApi
        ApiOptions:
          Type: Api
          Properties:
            Path: /submit
            Method: OPTIONS
            RestApiId: !Ref ServerlessRestApi

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        AllowCredentials: true

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit"
